config/routes.rb
Rails.application.routes.draw do

  resources :comments
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :editors do
    collection do
    get :info
  end
  resources :comments
end

  get 'control_users/index'

  get 'home/index'

  root 'home#index'

  resources :teams

  devise_for :users, :controllers => { registrations: 'registrations' }

  

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :editor
end

app/models/editor.rb
class Editor < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: true, length: { maximum: 100 }
  validates :post, presence: true
  validates :tags, presence: true
  validates :user, presence: true

  	def self.search(query)
		where("tags like?", "%#{query}%")
	end
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :editors

  enum role: [:normal_user, :admin]

  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :team, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  private
    def user_not_authorized
    	flash[:notice] = "Você não possui permissão para fazer esta ação!"
    	redirect_to(request.referrer || root_path)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @editor = Editor.find(params[:editor_id])
    @comment = @editor.comments.create(params[:comment].permit(:name, :body))

    redirect_to editor_path(@editor)
  end

  def destroy
    @editor = Editor.find(params[:editor_id])
    @comment = @editor.comments.find(params[:id])
    @comment.destroy

    redirect_to editor_path(@editor)
  end
end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.all 
  	authorize @users
  end
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  before_action :set_editor, only: [:show, :edit, :update, :destroy]

  # GET /editors
  # GET /editors.json
  def index
    if params[:search]
      @editors = Editor.order(created_at: :desc).search(params[:search]).paginate(:page => params[:page], :per_page => 5)
    else
      @editors = Editor.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
    end
  end

  def info
    if params[:search]
      @editors = Editor.order(created_at: :desc).search(params[:search]).paginate(:page => params[:page], :per_page => 5)
    else
      @editors = Editor.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
    end
  end

  # GET /editors/1
  # GET /editors/1.json
  def show
  end

  # GET /editors/new
  def new
    @editor = Editor.new
  end

  # GET /editors/1/edit
  def edit
  end

  # POST /editors
  # POST /editors.json
  def create
    @editor = Editor.new(editor_params)

    respond_to do |format|
      if @editor.save
        format.html { redirect_to @editor, notice: 'Texto criado com sucesso!' }
        format.json { render :show, status: :created, location: @editor }
      else
        format.html { render :new }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /editors/1
  # PATCH/PUT /editors/1.json
  def update
    respond_to do |format|
      if @editor.update(editor_params)
        format.html { redirect_to @editor, notice: 'Texto editado com sucesso!' }
        format.json { render :show, status: :ok, location: @editor }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /editors/1
  # DELETE /editors/1.json
  def destroy
    @editor.destroy
    respond_to do |format|
      format.html { redirect_to editors_url, notice: 'Editor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editor
      @editor = Editor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def editor_params
      params.require(:editor).permit(:title, :post, :tags, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_in_params
  	params.require(:user).permit(:email, :password)
  end

  def sign_up_params
    params.require(:user).permit(:name, :team, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :team, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= raw(comment.body) %></p>
	</div>

<% if user_signed_in? %>
<% if policy(@editor).index? %>
	<p><%= link_to 'Deletar', [comment.editor, comment],
					method: :delete,
					class: "button",
					data: { confirm: 'Você tem certeza?' } %>
<% end %>
<% end %>
</div>

app/views/comments/_fform.html.erb
<%= form_for([@editor, @editor.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%=f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%=f.cktext_area :body %>
	</p>
	<br>
	<p>
		<% = f.submit %>
	</p>
	<% end %>

app/views/comments/_form.html.erb
<%= form_for([@editor, @editor.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.cktext_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Editor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.editor %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Editor:</strong>
  <%= @comment.editor %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/control_users/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag     params[:controller] %>
  <%= javascript_include_tag  params[:controller] %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Lista de Usuários</h1>

<table>
  <thead>
    <tr>
      <th>E-mail</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Home', home_index_path %>

app/views/editors/_form.html.erb
<%= form_for(@editor, remote:true) do |f| %>
  <% if @editor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editor.errors.count, "error") %> prohibited this editor from being saved:</h2>

      <ul>
      <% @editor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.cktext_area :post %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editors/create.js.erb
var qtdErrors = <%= @editor.errors.count %>;

	if (qtdErrors > 0) {
		$.notify("Ocorreu algum erro! Cheque se todas as informações estão preenchidas!", "error"); }

app/views/editors/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag  "notify" %>
<% end %>
<div class="container">
<h1>Editando Texto</h1>

<%= render 'form' %>

<%= link_to 'Show', @editor %> |
<%= link_to 'Back', editors_path %>
</div>

app/views/editors/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag     params[:controller] %>
  <%= javascript_include_tag  'application', 'ckeditor.js'  %>
<% end %>

<p id="notice"><%= notice %></p>
<div class="container">

<h2>Busca de Textos</h2>

<%= form_tag(editors_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Digite sua busca...', size: 50 %>
  <%= submit_tag "Busque!", :class => "btn btn-danger" %>
<% end %>
<br><hr><br>

    <h2>Posts</h2>
    <% @editors.each do |post| %>
    <div class="post_wrapper">
      <h3 class="title"><%= link_to post.title, post %></h3>
      <p class="tags">Tags: <%= post.tags %></p>
    </div>
    <% end %>
<%= will_paginate @editors %>
<br>
<%= link_to 'Administração de Textos', info_editors_path %> <br>
</div>

app/views/editors/info.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag     params[:controller] %>
  <%= javascript_include_tag  'application', 'ckeditor.js'  %>
<% end %>

<% if user_signed_in? %>
<% if policy(@editors).index? %>
<div class="container">
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>Tags</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @editors.each do |editor| %>
      <tr>
        <td><%= editor.title %></td>
        <td><%= editor.post %></td>
        <td><%= editor.tags %></td>
        <td><%= editor.user.name %></td>
        <td><%= link_to 'Show', editor, :class => "btn btn-danger" %></td>
        <td><%= link_to 'Edit', edit_editor_path(editor), :class => "btn btn-danger" %></td>
        <td><%= link_to 'Destroy', editor, method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @editors %>
<br><hr>
<%= link_to 'Novo Texto', new_editor_path, :class => "btn btn-danger" %> <br>
<% end %>
<% else %>

<h2>Você não tem permissão!</h2>
<%= link_to 'Voltar', home_index_path, :class => "btn btn-danger" %>
<% end %>

<h2>Você não tem permissão!</h2>
<%= link_to 'Voltar', home_index_path, :class => "btn btn-danger" %>
</div>

app/views/editors/new.html.erb
<div id="container">
<% content_for :head do %>
  <%= javascript_include_tag  "notify" %>
<% end %>

<h1>Novo Texto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', editors_path %>
</div>

app/views/editors/show.html.erb
<p id="notice"><%= notice %></p>

    <style type="text/css">
    .container {
        margin: 20px;
    }
    .title {
    	font-size: 30px;
    }
    .tags {
    	font-size: 20px;
    }
    </style>

<div class="container">
<p class="title">
  <strong><%= @editor.title %></strong>
</p>

<p>
  <%= raw(@editor.post) %>
</p>

<p class="tags">
  <strong>Tags:</strong>
  <%= @editor.tags %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @editor.user.name %>
</p>

<br><hr>

<div id="comments">
  <h2><%= @editor.comments.count %> Comentários</h2>
  <%= render @editor.comments %>
  <h3>Escreva um comentário!</h3>
  <%= render "comments/form" %>

</div>

</div>

<%= link_to 'Editar', edit_editor_path(@editor) %> |
<%= link_to 'Voltar', editors_path %>

app/views/editors/update.js.erb
var qtdErrors = <%= @editor.errors.count %>;

	if (qtdErrors > 0) {
		$.notify("Ocorreu algum erro! Cheque se todas as informações estão preenchidas!", "error"); }
	else {
		$.notify("Texto editado e salvo!", "success"); }

app/views/home/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag     params[:controller] %>
  <%= javascript_include_tag  params[:controller] %>
<% end %>

<div class="container">
<p id="notice"><%= notice %></p>
  <head>
    <meta charset='utf-8'> 
  </head>
  <body>
  
 	<% if user_signed_in? %>
      <ul>
        <h3>Bem vindo!</h3>
        <li><%= current_user.email %></li>
      </ul>
  <% end %>

  <span class="container">
  <span class="admin"><%= link_to image_tag("http://thegoat.com.br/wp-content/uploads/2016/07/011.png"), info_editors_path %>    </span>
  </span>

  </body>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The GOAT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'ckeditor.js' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>
          
          <ul class="topnav">
            <li class="bodinho"> <%= link_to image_tag("http://thegoat.com.br/wp-content/uploads/2016/07/100px.png"), home_index_path %></li>
            <li><%= link_to " NBA", editors_path, :class => "glyphicon glyphicon-fire" %></li>
            <% if user_signed_in? %>
              <li><%= link_to " Sair", destroy_user_session_path, :class => "glyphicon glyphicon-log-out", method: :delete %></li>
            <% else %>
              <li><%= link_to " Cadastro", new_user_registration_path, :class => "glyphicon glyphicon-user" %> </li>
              <li><%= link_to " Entrar", user_session_path, :class => "glyphicon glyphicon-log-in" %></li>
            <% end %>
            <li class="icon"><a href="javascript:void(0);" style="font-size:30px;" onclick="myFunction()">☰</a></li>
          </ul>

<%= yield %>

</body>

<footer>
  <hr>
  <a href="http://www.twitter.com/TheGOATbr" target="_blank"><img src="http://findicons.com/files/icons/2052/social_network/32/twitter.png"></a>
  <a href="https://www.facebook.com/theGOATbr/" target="_blank"><img src="http://www.woottonbassettcameraclub.org.uk/wp-content/uploads/2015/06/facebook.png"></a>
  <br><em>&copy; Direitos reservados à Pedro Teixeira.</em>
</footer>

</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>